image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1769.97552,    0.     ,  640.16967,
            0.     , 1768.505  ,  476.89087,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.066922, 0.319323, -0.000471, -0.002405, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1771.47883,    0.     ,  638.14238,    0.     ,
            0.     , 1772.12224,  476.9671 ,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
